---
- hosts: netology
  become: true
  gather_facts: true
  tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:

    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- ansible.builtin.import_playbook: nginx.yaml

- ansible.builtin.import_playbook: db.yaml
